### ISSUE TITLE
Ember support

### ISSUE THREAD

**Issue by karellm** [josemarluedke/ember-cli-segment#12]
Looking at the code, I looks like you do no support anything after Ember `1.10`. Is it intended? Any plan on supporting more recent versions?

**Comment by josemarluedke** [comment]
@karellm I didn't have the chance to work in testing with the new versions of Ember and upgrading it. I would love a PR with the necessary changes to support it.

**Comment by josescasanova** [comment]
+1

**Comment by shved270189** [comment]
+1

**Comment by kmiyashiro** [comment]
I'd be willing to work on this, but I'm not familiar with addon upgrading. Specifically, if I upgrade ember-cli to 1.x, would that break anything, or does that only pertain to the development of the addon itself?

**Comment by kmiyashiro** [comment]
I started a PR (#16) but I'm not sure I know what I'm doing. Any pointers would be appreciated.

**Comment by josemarluedke** [comment]
Here's a plan to upgrade newer versions of ember.

With @kmiyashiro pr (#16) we can get the addon compatible with ember 1.13 series and we can release a version 0.1.0 with that. 

After having that landed we will start working toward v1.0 with some refactoring, improvements and possible api changes. I have created a milestones [v1.0.x](https://github.com/josemarluedke/ember-cli-segment/milestones/v1.0.x) with some ideas that I have, also I would love to see some feedbacks about it and new ideas.

**Comment by josemarluedke** [comment]
Just pushed v0.1.0 to NPM supporting ember > 1.13 and ember 2.x.
