### ISSUE TITLE
Ability to pull key from server

### ISSUE THREAD

**Issue by thedug** [josemarluedke/ember-cli-segment#15]
We'd like to pull our key from our server so that our app can be statically hosted and provide configuration based on the domain where the site is hosted.

By the time we are able to pull the configuration from our api the segment module is already loaded. 

Is there a way to delay this?

**Comment by josemarluedke** [comment]
Closing this since it's been a long time and there was no more requests like this.

If you still need to work around this, feel free to reopen this.
