### ISSUE TITLE
Make segment object available in mixed objects

### ISSUE THREAD

**Issue by Irio** [josemarluedke/ember-cli-segment#2]
Right now, you have to use functions of `segmentMixin` directly in the component object. Would be nice to use them through `segment` object, as in routes, for instance.

```javascript
import Ember from 'ember';
import segmentMixin from 'ember-cli-segment/mixin';

export default Ember.Component.extend(segmentMixin, {
  init: function() {
    this.trackEvent('Event name');
  }
});
```

**Comment by JackCA** [comment]
and I struggled to figure out this is how you use the mixin since I don't believe it's referenced in the Docs...

**Comment by josemarluedke** [comment]
@JackCA In the readme we just show how to import the mixin, but make sense to include a example of usage. Thanks for pointing that out.

**Comment by JackCA** [comment]
@Irio do you think if this was explicitly mentioned in the docs, you'd still want the feature?

**Comment by josemarluedke** [comment]
Closing this since the right path is move it to a service.

**Comment by jpalmer1026** [comment]
Is there an example somewhere of how to use the mixin? Or how to move it to a service and use the service instead? I tried the mixin approach but the window.analytics object is undefined so when I call trackEvent on the mixin, nothing happens.

**Comment by josemarluedke** [comment]
There is a service already shipped. You can use it as `segment: Ember.inject.service()`.

If your window. analytics is undefined, make sure you have the correct keys and that the addon is adding the segment scripts.

**Comment by jpalmer1026** [comment]
@josemarluedke Thanks for the response. Looks like the keys are correct. How can I ensure that the addon is adding the segment scripts?

**Comment by josemarluedke** [comment]
Take a look at the source code of you web page.
