### ISSUE TITLE
Remove ember-getowner-polyfill

### ISSUE THREAD

**Issue by josemarluedke** [josemarluedke/ember-cli-segment#21]
Using `ember-getowner-polyfill` on a ember 2.3 app causes a deprecation warnings

<img width="1405" alt="screen shot 2016-01-27 at 3 38 27 pm" src="https://cloud.githubusercontent.com/assets/230476/12632339/1a800462-c50c-11e5-9ff6-f642618af86e.png">

Maybe we can remove this dependency for version 1.0 and only support ember > 2.3?

**Comment by kmiyashiro** [comment]
This is a bug in the polyfill and `Ember.getOwner`, fixing both would get rid of the deprecation https://github.com/emberjs/ember.js/issues/12866

**Comment by josemarluedke** [comment]
Closed by #25.
