### ISSUE TITLE
`"disableAnalytics": true` not working

### ISSUE THREAD

**Issue by rduque1** [josemarluedke/ember-cli-segment#22]
In my `.ember-cli` file I set `"disableAnalytics": true` but still it is doing all the calls to segment.
Did I miss something, or did something wrong. Or is it a bug?

Thanks

**Comment by josemarluedke** [comment]
Hello @rduque1. The `"disableAnalytics": true` is for ember CLI sending analytics information about the use of the CLI itself, there is nothing to do with the segment integration. 

If you would like to disable the segment integration, just remove the `segment ` configuration from you `config/environment.js`.
