### ISSUE TITLE
Bugsnag not available

### ISSUE THREAD

**Issue by anthonycollini** [josemarluedke/ember-cli-segment#30]
It seems that segment isn't loaded in the `init` or `activate` hooks in the application route. When I try to call `Bugsnag` from this point in the application, it says it's not defined.

I also need to use the integration in the build process of the app, and report errors to Bugsnag.

Would you be able to provide some guidance on how to ensure it gets loaded immediately, or for me to be able to manually ensure it's available?

Thanks,

Anthony

**Comment by josemarluedke** [comment]
Hey @anthonycollini! For Bugsnag integration, I would recommend using [ember-cli-bugsnag](https://github.com/binhums/ember-cli-bugsnag) instead of having segment add it.

Hope that can help you.
