### ISSUE TITLE
High numbers of anons causing high Segment costs

### ISSUE THREAD

**Issue by tamzinblake** [josemarluedke/ember-cli-segment#40]
I was wondering if it would be possible to skip or delay sending events to Segment for unidentified users, and whether a PR would be accepted that enables that.

We had an issue where sending trackEvents to Segment without having properly identified our users was leading to cost overrun. We already had some code in our identifyUser block that skipped the call if we didn't have a valid user id yet, but also had to add some code to our function that calls trackEvent in order to make sure that if a user was not identified the event isn't sent.  However there were also other calls that we weren't making directly, like ember-cli-segment's built-in page tracking, that we didn't have a way of blocking for anons (though we ended up turning off that feature with config).

Obviously skipping these tracking calls for unidentified users is less-than-ideal, if the user will be identified but it hasn't happened yet; it would maybe be better to defer tracking until after identify is successful. Perhaps a solution would be some sort of promise chain, starting with whatever should trigger a successful identify and then the tracking calls chained after that.

So I guess my question is, any thoughts, am I missing something obvious that's already here, and would this be better as a PR or a fork?

**Comment by thomblake** [comment]
@josemarluedke Any thoughts on this?

**Comment by josemarluedke** [comment]
I believe it would be interesting to have a feature that would disable the track page when a user is not authenticated. Provided that you can specify when the user is authenticated and having a configuration to enable this behavior. It would love to get a PR for that. 

On the other hand I'm not sure if having the track being delayed is a good idea. Depending of the application, a user could visit many pages and never hard refresh your app as well as never login, the memory usage could growth a lot. Instead, I would argue to have some kind of hook that would allow your application to deal with that logic.

**Comment by thomblake** [comment]
Thanks for the response! I'll look into a PR. Good point about the memory issue; I'll keep that in mind.

**Comment by josemarluedke** [comment]
Closing this per inactivity. Feel free to reopen if you think it is still relevant.
