### ISSUE TITLE
Uncaught Error: Could not find module @ember/service

### ISSUE THREAD

**Issue by kalyankiranb** [josemarluedke/ember-cli-segment#52]
I am getting this error when using this addon.
I see this in chrome developer tools when I am trying to visit the page.
According to the readme, "The add-on exposes a service that you can inject in ...". I am injecting this in my controller and the above error is thrown when visiting that page and the page is not loading. Did I miss any step or my ember version is the problem? I am using ember 1.12.

**Comment by josemarluedke** [comment]
Unfortunately Ember 1.12 is not supported. However, your error is probably solvable by upgrading Ember CLI and Babel.
