### ISSUE TITLE
npm ERR! git /opt/build/repo/node_modules/ember-cli-segment: Appears to be a git repo or submodule.

### ISSUE THREAD

**Issue by smartens80** [josemarluedke/ember-cli-segment#58]
Seems that the '.git' folder has been included in the NPM package which results in 'ERR! git /opt/build/repo/node_modules/ember-cli-segment: Appears to be a git repo or submodule.' on npm install. 

Only seems to affect 3.2.0 at this time.

**Comment by josemarluedke** [comment]
Thanks for letting me know. I have fixed in v3.2.1.
