### ISSUE TITLE
Possible to prevent logging some transitions?

### ISSUE THREAD

**Issue by jclem** [josemarluedke/ember-cli-segment#7]
Updating a query param, for example, even via `replaceState` causes a page view to be logged. This is problematic in cases where a user typing into a search field updates a query param to make the search bookmark-able, which should not be individually tracked.

Ember's query param behavior always causes a `didTransition` event, so I'm not sure how to prevent this.

**Comment by duboff** [comment]
:+1:  Same problem

**Comment by josemarluedke** [comment]
In order to achieve this, you would need to disable the default tracking and only call `trackPageView` where you need it.

Closing this since it's open for more than a year. If you still need need to work around this, feel free to reopen.
