### ISSUE TITLE
Ember-CLI container.lookup/lookupFactory is deprecated

### ISSUE THREAD

**Issue by sukima** [josemarluedke/ember-cli-segment#8]
Ember-CLI 0.2.5 introduced the following deprecated APIs:

> DEPRECATION: `lookupFactory` was called on a Registry. The `initializer` API no longer receives a container, and you should use an `instanceInitializer` to look up objects from the container. See http://emberjs.com/guides/deprecations#toc_deprecate-access-to-instances-in-initializers for more details.

> DEPRECATION: `lookup` was called on a Registry. The `initializer` API no longer receives a container, and you should use an `instanceInitializer` to look up objects from the container. See http://emberjs.com/guides/deprecations#toc_deprecate-access-to-instances-in-initializers for more details.

The relevant source is in the [initializer line 5](https://github.com/josemarluedke/ember-cli-segment/blob/master/addon/initializer.js#L5) and [line 13](https://github.com/josemarluedke/ember-cli-segment/blob/master/addon/initializer.js#L13).

**Comment by josemarluedke** [comment]
Thanks for reporting it @sukima. Would you like to send a PR with the changes necessary?
