### ISSUE TITLE
[Ember 3.26+] Deprecation Warning: Implicit Injection is now deprecated.  

### ISSUE THREAD

**Issue by RQMdev** [josemarluedke/ember-cli-segment#86]
Hi,

Since upgrading to Ember v3.26 we now have a deprecation warning about segment service being injected implicitly.
Here are some more info on the deprecation strategy they're using considering implicit injection : 
https://emberjs.github.io/rfcs/0680-implicit-injection-deprecation.html.

The first step would be to explicitly import the Segment Service but as this is doing things silently under the hoods. I don't know where to start to help make it totally explicit.

Thank you

**Comment by Duder-onomy** [comment]
FWIW, This seems to be fixed since for around 2 years now: https://github.com/josemarluedke/ember-cli-segment/blame/d7763912d0ea09a66657ddc34ada0a67d851c1b1/addon/services/segment.js#L39
